### ISSUE TITLE
"Learn Python" hyperlink in README.md is currently broken

### ISSUE THREAD

**Issue by awillats** [pineapplemachine/PyDwarf#7]
looks like it currently points to PyDwarf/blob/master/learnpythonthehardway.org/book/ex0.html
maybe it could be directed to 
[https://learnpythonthehardway.org/book/ex0.html](https://learnpythonthehardway.org/book/ex0.html)

**Comment by pineapplemachine** [comment]
Whoops, looks like it needed an `http://` or `https://` at the start to not be treated as a relative URL path. Thanks for pointing that out!

I made the correction just now in https://github.com/pineapplemachine/PyDwarf/commit/6c41830931614bb8a43710be72a4ede9288e517f. But if you had any additional or better resources in mind, I'd be happy to take a look at a PR.

**Comment by awillats** [comment]
sounds good! I'm working on following the install instructions on a new mac so i'll probably make one PR with a few suggestions
